Repository uplim/triplate-app, pull requests merged in 2023-04, with the labels that each got.

#42 :metal: homeページをマークアップ
  front/.storybook/main.js
  front/src/components/Avatars/AvatarWithText.tsx
  front/src/components/Avatars/index.ts
  front/src/components/Cards/CardTravelink.tsx
  front/src/components/Cards/index.ts
  front/src/components/Chips/ChipTag.tsx
  front/src/components/Chips/index.ts
  front/src/components/Tabs/TabHome.tsx
  front/src/components/Tabs/index.ts
  front/src/pages/home.tsx
  front/src/pages/mypage.tsx
  front/src/stories/components/Avatars/Avatar.stories.tsx
  front/src/stories/components/Avatars/AvatarWithText.stories.tsx
  front/src/stories/components/Cards/CardTravelink.stories.tsx
  front/src/stories/components/Chips/ChipTag.stories.tsx
  front/src/stories/components/Tabs/TabHome.stories.tsx
  front/src/styles/components/Avatars/AvatarWithText.module.scss
  front/src/styles/components/Cards/CardTravelink.module.scss
  front/src/styles/components/Chips/ChipTag.module.scss
  front/src/styles/components/Grids/GridIconWithText.module.scss
  front/src/styles/components/Tabs/TabHome.module.scss
  front/src/styles/pages/Home.module.scss
  front/src/styles/pages/Mypage.module.scss
Labels: 🥳LGTM, Markup

#60 🧑‍🍳 makefileいい感じにする
  Makefile
  README.md
  front/Dockerfile
  front/package.json
  front/yarn.lock
Labels: Review Required, Refactor

#58 🇹🇩 chromeのエラー治す
  front/next.config.js
Labels: 🥳LGTM, Refactor

#56 🈂️ stylesディレクトリに移す
  .github/PULL_REQUEST_TEMPLATE.md
  front/src/components/Avatars/Avatar.tsx
  front/src/components/Avatars/AvatarWithText.tsx
  front/src/components/Buttons/ButtonFill.tsx
  front/src/components/Buttons/ButtonIconRound.tsx
  front/src/components/Buttons/ButtonOutline.tsx
  front/src/components/Cards/CardTravelink.tsx
  front/src/components/Chips/ChipTag.tsx
  front/src/components/Containers/Container.tsx
  front/src/components/Containers/index.ts
  front/src/components/Grids/GridIconWithText.tsx
  front/src/components/Headers/Header.tsx
  front/src/components/Icons/IconWithText.tsx
  front/src/components/Layouts/Layout.tsx
  front/src/components/Navigations/NavigationBottom.tsx
  front/src/components/Tabs/TabDays.tsx
  front/src/components/Tabs/TabHome.tsx
  front/src/pages/home/index.tsx
  front/src/pages/mypage/index.tsx
  front/src/styles/components/Avatars/Avatar.styles.ts
  front/src/styles/components/Avatars/AvatarWithText.styles.ts
  front/src/styles/components/Buttons/ButtonFill.styles.ts
  front/src/styles/components/Buttons/ButtonIconRound.styles.ts
  front/src/styles/components/Buttons/ButtonOutline.styles.ts
  front/src/styles/components/Cards/CardTravelink.styles.ts
  front/src/styles/components/Chips/ChipTag.styles.ts
  front/src/styles/components/Containers/Container.styles.ts
  front/src/styles/components/Grids/GridIconWithText.styles.ts
  front/src/styles/components/Headers/Header.styles.ts
  front/src/styles/components/Icons/IconWithText.styles.ts
  front/src/styles/components/Layouts/Layout.styles.ts
  front/src/styles/components/Navigations/NavigationBottom.styles.ts
  front/src/styles/components/Tabs/TabDays.styles.ts
  front/src/styles/components/Tabs/TabHome.styles.ts
  front/src/styles/pages/home/index.styles.ts
  front/src/styles/pages/mypage/index.styles.ts
Labels: Review Required, Refactor

#62 🎩 classNameつけない
  front/package.json
  front/src/components/Cards/CardTravelink.tsx
  front/src/styles/components/Cards/CardTravelink.styles.ts
Labels: 🥳LGTM, Refactor

#50 🕗 Header修正
  front/src/components/Containers/Container.tsx
  front/src/components/Headers/Header.tsx
  front/src/styles/components/Containers/Container.styles.ts
  front/src/styles/components/Headers/Header.styles.ts
Labels: 🥳LGTM, Markup

#65 💿 CD追加
  .github/workflows/dispatch-repo-updated.yml
  front/src/pages/index.tsx
Labels: CI/CD

#68 👍 動作確認
  front/src/pages/index.tsx
Labels: CI/CD

#69 動作確認
  .github/workflows/dispatch-repo-updated.yml
  front/src/pages/index.tsx
Labels: CI/CD

#71 👍 syncリポジトリのコミットメッセージをプルリクURLにする
  .github/workflows/dispatch-repo-updated.yml
  front/src/pages/index.tsx
Labels: Review Required, CI/CD

#73 💯 リポジトリをsyncする
  .github/workflows/dispatch-repo-updated.yml
  front/src/pages/index.tsx
Labels: Review Required, CI/CD

#53 🌻 travelinkページのマークアップ
  front/public/images/thumbnail_sample.jpg
  front/src/components/Buttons/ButtonIconWithText.tsx
  front/src/components/Buttons/index.ts
  front/src/components/Icons/IconWithText.tsx
  front/src/components/Images/ImageThumbnail.tsx
  front/src/components/Images/index.ts
  front/src/components/Tabs/TabDays.tsx
  front/src/components/Tabs/TabDaysWithTravelink.tsx
  front/src/components/Tabs/TabSample.tsx
  front/src/components/Tabs/index.ts
  front/src/pages/travelink/[travelinkId]/index.tsx
  front/src/stories/components/Buttons/ButtonIconWithText.stories.tsx
  front/src/stories/components/Images/ImageThumbnail.stories.tsx
  front/src/stories/components/Tabs/TabDays.stories.tsx
  front/src/stories/components/Tabs/TabDaysWithTravelink.stories.tsx
  front/src/stories/components/Tabs/TabSample.stories.tsx
  front/src/stories/cores/Icons.mdx
  front/src/styles/components/Buttons/ButtonIconWithText.styles.ts
  front/src/styles/components/Images/ImageThumbnail.styles.ts
  front/src/styles/components/Tabs/TabDaysWithTravelink.styles.ts
  front/src/styles/components/Tabs/TabSample.styles.ts
  front/src/styles/pages/travelink/[travelinkId]/Travelink.styles.ts
Labels: 🥳LGTM, Markup

#75 🅰️ アクセシビリティを考慮したmodalシステムを作成
  .github/workflows/deploy-storybook.yml
  front/.storybook/preview.tsx
  front/package.json
  front/src/components/Links/LinkItemWithIcon.tsx
  front/src/components/Links/index.ts
  front/src/components/Modals/BaseHalfModal.tsx
  front/src/components/Modals/ModalEdit.tsx
  front/src/components/Modals/index.ts
  front/src/hooks/modals/index.ts
  front/src/hooks/modals/useAriaHidden.ts
  front/src/hooks/modals/useDisableScroll.ts
  front/src/hooks/modals/useDisclosure.ts
  front/src/hooks/modals/useFocusTrap.ts
  front/src/hooks/modals/useHalfModal.ts
  front/src/pages/index.tsx
  front/src/stories/components/Modals/BaseHalfModal.stories.tsx
  front/src/stories/components/Modals/ModalEdit.stories.tsx
  front/src/styles/components/Buttons/ButtonIconWithText.styles.ts
  front/src/styles/components/Cards/CardTravelink.styles.ts
  front/src/styles/components/Forms/FormCreate.styles.ts
  front/src/styles/components/Headers/Header.styles.ts
  front/src/styles/components/Icons/IconWithText.styles.ts
  front/src/styles/components/Links/LinkItemWithIcon.styles.ts
  front/src/styles/components/Modals/BaseHalfModal.styles.ts
  front/src/styles/components/Modals/ModalEdit.styles.ts
  front/src/styles/components/Navigations/NavigationBottom.styles.ts
  front/src/styles/components/Tabs/TabHome.styles.ts
  front/src/styles/globalStyle.ts
  front/yarn.lock
Labels: Markup, Review Required

#87 👂 リスト表示グリッド表示切り替え
  front/src/components/Cards/CardTravelink.tsx
  front/src/components/Tabs/TabHome.tsx
  front/src/pages/home/index.tsx
  front/src/stories/components/Cards/CardTravelink.stories.tsx
  front/src/stories/components/Tabs/TabHome.stories.tsx
  front/src/styles/components/Avatars/AvatarWithText.styles.ts
  front/src/styles/components/Buttons/ButtonFill.styles.ts
  front/src/styles/components/Buttons/ButtonIconRound.styles.ts
  front/src/styles/components/Buttons/ButtonIconWithText.styles.ts
  front/src/styles/components/Buttons/ButtonOutline.styles.ts
  front/src/styles/components/Cards/CardTravelink.styles.ts
  front/src/styles/components/Chips/ChipTag.styles.ts
  front/src/styles/components/Icons/IconWithText.styles.ts
  front/src/styles/components/Modals/BaseHalfModal.styles.ts
  front/src/styles/components/Navigations/NavigationBottom.styles.ts
  front/src/styles/components/Tabs/TabHome.styles.ts
  front/src/styles/globalStyle.ts
  front/src/styles/pages/mypage/index.styles.ts
  front/src/styles/theme.ts
Labels: Markup, Review Required

#90 ボトムナビゲーションの後ろの要素が隠れる
  front/src/components/Navigations/NavigationBottom.tsx
  front/src/styles/components/Navigations/NavigationBottom.styles.ts
Labels: 🥳LGTM, Markup

#82 🪡トラベリンクのリストを作成
  front/public/linkIcon/linkIcon_ledger.svg
  front/public/linkIcon/linkIcon_link.svg
  front/public/linkIcon/linkIcon_pin.svg
  front/src/components/Cards/CardTravelListItem.tsx
  front/src/components/Cards/index.ts
  front/src/stories/components/Cards/CardTravelListItem.stories.tsx
  front/src/styles/components/Cards/CardTravelListItem.styles.ts
Labels: 🥳LGTM, Markup

#88 🐙 travelinkページのModalコンポーネント作成
  front/.eslintrc.js
  front/src/components/Avatars/AvatarWithText.tsx
  front/src/components/Avatars/index.ts
  front/src/components/Buttons/ButtonIconWithText.tsx
  front/src/components/Buttons/ButtonIconWithTextHorizontal.tsx
  front/src/components/Buttons/index.ts
  front/src/components/Cards/CardMemo.tsx
  front/src/components/Cards/index.ts
  front/src/components/Chips/ChipTag.tsx
  front/src/components/Chips/ChipTagList.tsx
  front/src/components/Chips/index.ts
  front/src/components/Forms/FormAuthority.tsx
  front/src/components/Forms/index.ts
  front/src/components/Links/LinkIconWithTextHorizontal.tsx
  front/src/components/Links/LinkItemWithIcon.tsx
  front/src/components/Links/index.ts
  front/src/components/Modals/BaseHalfModal.tsx
  front/src/components/Modals/ModalEdit.tsx
  front/src/components/Modals/ModalMember.tsx
  front/src/components/Modals/ModalMemo.tsx
  front/src/components/Modals/ModalQr.tsx
  front/src/components/Modals/ModalShare.tsx
  front/src/components/Modals/index.ts
  front/src/components/Selects/SelectAuthority.tsx
  front/src/components/Selects/index.ts
  front/src/components/Tabs/TabHome.tsx
  front/src/components/Tabs/TabSample.tsx
  front/src/hooks/cards/index.ts
  front/src/hooks/cards/useCardMemo.ts
  front/src/pages/index.tsx
  front/src/pages/travelink/[travelinkId]/index.tsx
  front/src/stories/components/Cards/CardMemo.stories.tsx
  front/src/stories/components/Chips/ChipTag.stories.tsx
  front/src/stories/components/Chips/ChipTagList.stories.tsx
  front/src/stories/components/Forms/FormAuthority.stories.tsx
  front/src/stories/components/Modals/ModalMember.stories.tsx
  front/src/stories/components/Modals/ModalMemo.stories.tsx
  front/src/stories/components/Modals/ModalQr.stories.tsx
  front/src/stories/components/Modals/ModalShare.stories.tsx
  front/src/stories/components/Selects/SelectAuthority.stories.tsx
  front/src/stories/cores/Icons.mdx
  front/src/styles/components/Avatars/AvatarWithText.styles.ts
  front/src/styles/components/Buttons/ButtonIconWithText.styles.ts
  front/src/styles/components/Buttons/ButtonIconWithTextHorizontal.styles.ts
  front/src/styles/components/Cards/CardMemo.styles.ts
  front/src/styles/components/Chips/ChipTag.styles.ts
  front/src/styles/components/Chips/ChipTagList.styles.ts
  front/src/styles/components/Links/LinkIconWithTextHorizontal.styles.ts
  front/src/styles/components/Modals/ModalMember.styles.ts
  front/src/styles/components/Modals/ModalMemo.styles.ts
  front/src/styles/components/Modals/ModalQr.styles.ts
  front/src/styles/components/Modals/ModalShare.styles.ts
  front/src/styles/components/Selects/SelectAuthority.styles.ts
  front/src/styles/pages/travelink/[travelinkId]/Travelink.styles.ts
Labels: 🥳LGTM, Markup

#96 🖲️ 名称変更
  .github/workflows/dispatch-repo-updated.yml
  Makefile
  README.md
  docker-compose.yml
  front/package.json
  front/src/components/Cards/CardTripListItem.tsx
  front/src/components/Cards/CardTriplink.tsx
  front/src/components/Cards/index.ts
  front/src/components/Modals/ModalMemo.tsx
  front/src/components/Tabs/TabDaysWithTriplink.tsx
  front/src/components/Tabs/TabHome.tsx
  front/src/components/Tabs/index.ts
  front/src/pages/home/index.tsx
  front/src/pages/index.tsx
  front/src/pages/triplink/[triplinkId]/index.tsx
  front/src/stories/components/Cards/CardMemo.stories.tsx
  front/src/stories/components/Cards/CardTripListItem.stories.tsx
  front/src/stories/components/Cards/CardTriplink.stories.tsx
  front/src/stories/components/Tabs/TabDaysWithTriplink.stories.tsx
  front/src/stories/components/Tabs/TabHome.stories.tsx
  front/src/styles/components/Cards/CardTripListItem.styles.ts
  front/src/styles/components/Cards/CardTriplink.styles.ts
  front/src/styles/components/Tabs/TabDaysWithTriplink.styles.ts
  front/src/styles/components/Tabs/TabHome.styles.ts
  front/src/styles/pages/triplink/[triplinkId]/triplink.styles.ts
  front/yarn.lock
Labels: 🥳LGTM, Refactor
