Repository uplim/triplate-app, pull requests merged in 2023-07, with the labels that each got.

#145 🌱 シードデータ作成
  front/firebase/scripts/seeder.ts
  front/firebase/seeds/firestore/triplates.json
  front/firebase/seeds/firestore/triplink.json
  front/firebase/seeds/firestore/users.json
  front/firebase/seeds/storage/images/users/C5Ja2gXGLeIXTjhWZbDiWUWe8Whd/triplates/060b3ff3-0b5a-4d8f-8c4f-13168750dfe1/day1.jpg
  front/firebase/seeds/storage/images/users/C5Ja2gXGLeIXTjhWZbDiWUWe8Whd/triplates/060b3ff3-0b5a-4d8f-8c4f-13168750dfe1/day2.jpg
  front/firebase/seeds/storage/images/users/C5Ja2gXGLeIXTjhWZbDiWUWe8Whd/triplates/060b3ff3-0b5a-4d8f-8c4f-13168750dfe1/day3.jpg
  front/src/components/Cards/CardTriplate.tsx
  front/src/components/Cards/CardTriplink.tsx
  front/src/hooks/modals/useModalSearchMap.ts
  front/src/redux/services/firestore/triplates/triplates.ts
  front/src/redux/services/firestore/triplinks/triplinks.ts
  front/src/redux/services/firestore/users/followers.ts
  front/src/redux/services/firestore/users/follows.ts
  front/src/redux/services/firestore/users/users.ts
  front/src/stories/components/Forms/FormUpdateUser.stories.tsx
  front/src/stories/components/Tabs/TabHome.stories.tsx
  front/src/utils/dates/calcStayDuration.ts
  front/src/utils/dates/formatTimestamp.ts
Labels: 🥳LGTM, Logic, Review Required

#146 🍞 トーストの作成
  front/.eslintrc.js
  front/.storybook/googleMapsDecorator.tsx
  front/src/components/Auths/CheckAuth.tsx
  front/src/components/Forms/FormCreateUser.tsx
  front/src/components/Navigations/NavigationBottom.tsx
  front/src/components/Toasts/Toast.tsx
  front/src/components/Toasts/ToastProvider.tsx
  front/src/components/Toasts/index.ts
  front/src/hooks/auths/useCheckAuth.ts
  front/src/hooks/auths/useSignOut.ts
  front/src/hooks/errors/useErrorBoundary.ts
  front/src/hooks/forms/useFormCreateUpdateTriplateSettings.ts
  front/src/hooks/modals/useModalSearchMap.ts
  front/src/hooks/toasts/index.ts
  front/src/hooks/toasts/useToast.ts
  front/src/hooks/toasts/useToastProvider.ts
  front/src/pages/[userId]/index.tsx
  front/src/pages/_app.tsx
  front/src/pages/home/index.tsx
  front/src/pages/index.tsx
  front/src/pages/settings/profile.tsx
  front/src/pages/triplate/[triplateId]/edit/settings.tsx
  front/src/pages/triplate/new.tsx
  front/src/pages/triplink/[triplinkId]/edit/index.tsx
  front/src/pages/triplink/[triplinkId]/edit/location.tsx
  front/src/pages/user/new.tsx
  front/src/redux/features/auths/authSlice.ts
  front/src/redux/features/errors/errorHandler.ts
  front/src/redux/features/errors/errorSlice.ts
  front/src/redux/features/index.ts
  front/src/redux/features/maps/mapSlice.ts
  front/src/redux/features/toasts/toastSlice.ts
  front/src/redux/features/users/userSlice.ts
  front/src/redux/store.ts
  front/src/redux/stores/index.ts
  front/src/stories/components/Toasts/Toast.stories.tsx
  front/src/styles/components/Toasts/Toast.styles.ts
  front/src/styles/theme.ts
Labels: Logic, Review Required

#150 👹 アクセシビリティを考慮したタブ
  front/src/components/Cards/CardTripListItem.tsx
  front/src/components/Tabs/Tab.tsx
  front/src/components/Tabs/TabContent.tsx
  front/src/components/Tabs/TabDaysWithTriplink.tsx
  front/src/components/Tabs/TabList.tsx
  front/src/components/Tabs/TabPanel.tsx
  front/src/components/Tabs/TabSample.tsx
  front/src/components/Tabs/TabTriplate.tsx
  front/src/components/Tabs/TabTriplink.tsx
  front/src/components/Tabs/Tabs.tsx
  front/src/components/Tabs/index.ts
  front/src/hooks/tabs/index.ts
  front/src/hooks/tabs/useTabNavigation.ts
  front/src/pages/index.tsx
  front/src/pages/triplate/[triplateId]/index.tsx
  front/src/pages/triplink/[triplinkId]/index.tsx
  front/src/redux/services/firestore/triplates/triplates.ts
  front/src/redux/services/firestore/triplinks/triplinks.ts
  front/src/stories/components/Tabs/TabDaysWithTriplink.stories.tsx
  front/src/stories/components/Tabs/TabSample.stories.tsx
  front/src/styles/components/Tabs/Tab.styles.ts
  front/src/styles/components/Tabs/TabDaysWithTriplink.styles.ts
  front/src/styles/components/Tabs/TabList.styles.ts
  front/src/styles/components/Tabs/TabPanel.styles.ts
  front/src/styles/components/Tabs/TabSample.styles.ts
  front/src/styles/components/Tabs/TabTriplate.styles.ts
  front/src/styles/components/Tabs/TabTriplink.styles.ts
  front/src/styles/components/Tabs/Tabs.styles.ts
Labels: 🥳LGTM, Markup
