Repository uplim/triplate-app, pull requests merged in 2023-05, with the labels that each got.

#107 🔥 Firebaseの基盤を作成
  Makefile
  docker-compose.yml
  front/Dockerfile
  front/firebase/.gitignore
  front/firebase/firebase.json
  front/firebase/scripts/initFirebase.sh
  front/firebase/scripts/resetDb.sh
  front/firebase/scripts/seeder.ts
  front/firebase/seeds/auth/test-user.json
  front/firebase/seeds/firestore/triplink.json
  front/firebase/seeds/firestore/users.json
  front/firebase/seeds/storage/thumbnail_sample.jpg
  front/firebase/seeds/storage/users/thumbnail_sample.jpg
  front/firebase/tsconfig.json
  front/firebase/utils/createTestUserIfNotExsists.ts
  front/firebase/utils/firebaseAdmin.ts
  front/firebase/utils/readJson.ts
  front/firebase/utils/searchFiles.ts
  front/firebase/utils/type.ts
  front/package.json
  front/src/components/Auths/CheckAuth.tsx
  front/src/components/Auths/index.ts
  front/src/hooks/auths/index.ts
  front/src/hooks/auths/useCheckAuth.ts
  front/src/lib/firebase.ts
  front/src/lib/firebaseAdmin.ts
  front/src/pages/_app.tsx
  front/src/pages/index.tsx
  front/src/redux/rootStore.ts
  front/src/redux/services/firestore/baseFirestoreApi.ts
  front/src/redux/services/firestore/index.ts
  front/src/redux/store.ts
  front/src/redux/stores/auths/authSlice.ts
  front/src/redux/stores/index.ts
  front/tsconfig.json
  front/yarn.lock
Labels: 🥳LGTM, Logic

#111 👍 ページ繋げる
  front/src/components/Buttons/ButtonIconRound.tsx
  front/src/components/Buttons/FloatingActionButton.tsx
  front/src/components/Forms/FormCreate.tsx
  front/src/components/Modals/ModalAddPlace.tsx
  front/src/components/Modals/ModalEdit.tsx
  front/src/components/Modals/ModalMemo.tsx
  front/src/components/Navigations/NavigationBottom.tsx
  front/src/components/Tabs/TabHome.tsx
  front/src/pages/[userId]/index.tsx
  front/src/pages/explore/index.tsx
  front/src/pages/help/index.tsx
  front/src/pages/help/triplate.tsx
  front/src/pages/home/index.tsx
  front/src/pages/mypage/index.tsx
  front/src/pages/notifications/[newsId].tsx
  front/src/pages/notifications/index.tsx
  front/src/pages/privacy.tsx
  front/src/pages/reader.tsx
  front/src/pages/search/index.tsx
  front/src/pages/settings/index.tsx
  front/src/pages/settings/location.tsx
  front/src/pages/settings/notifications.tsx
  front/src/pages/settings/profile.tsx
  front/src/pages/support.tsx
  front/src/pages/triplate/[triplateId]/edit/memory.tsx
  front/src/pages/triplate/[triplateId]/edit/settings.tsx
  front/src/pages/triplate/[triplateId]/index.tsx
  front/src/pages/triplate/new.tsx
  front/src/pages/triplink/[triplinkId]/edit/index.tsx
  front/src/pages/triplink/[triplinkId]/edit/location.tsx
  front/src/pages/triplink/[triplinkId]/edit/settings.tsx
  front/src/pages/triplink/[triplinkId]/edit/tabimemo/budget.tsx
  front/src/pages/triplink/[triplinkId]/edit/tabimemo/index.tsx
  front/src/pages/triplink/[triplinkId]/edit/tabimemo/items.tsx
  front/src/pages/triplink/[triplinkId]/edit/tabimemo/memo.tsx
  front/src/pages/triplink/[triplinkId]/index.tsx
  front/src/pages/triplink/new.tsx
  front/src/pages/user/new.tsx
  front/src/styles/pages/[userId]/index.styles.ts
  front/src/styles/pages/explore/index.styles.ts
Labels: Markup

#63 ⓂButtonSmall, ButtonFollowを追加
  front/src/components/Buttons/ButtonFollow.tsx
  front/src/components/Buttons/ButtonSmall.tsx
  front/src/components/Buttons/index.ts
  front/src/stories/components/Buttons/ButtonFollow.stories.tsx
  front/src/stories/components/Buttons/ButtonSmall.stories.tsx
  front/src/styles/components/Buttons/ButtonFollow.styles.ts
  front/src/styles/components/Buttons/ButtonSmall.styles.ts
Labels: Markup

#115 🛺 認証
  front/firebase/seeds/firestore/users.json
  front/firebase/utils/createTestUserIfNotExsists.ts
  front/src/components/Auths/CheckAuth.tsx
  front/src/components/Headers/Header.tsx
  front/src/components/Navigations/NavigationBottom.tsx
  front/src/hooks/auths/index.ts
  front/src/hooks/auths/useCheckAuth.ts
  front/src/hooks/auths/useSignIn.ts
  front/src/hooks/auths/useSignOut.ts
  front/src/pages/[userId]/index.tsx
  front/src/pages/auth.tsx
  front/src/pages/index.tsx
  front/src/pages/user/new.tsx
  front/src/redux/actions/clearAll.ts
  front/src/redux/actions/index.ts
  front/src/redux/rootStore.ts
  front/src/redux/services/firestore/baseFirestoreApi.ts
  front/src/redux/services/firestore/index.ts
  front/src/redux/services/firestore/users/users.ts
  front/src/redux/stores/auths/authSlice.ts
  front/src/redux/stores/index.ts
  front/src/redux/stores/maps/mapSlice.ts
  front/src/redux/stores/users/userSlice.ts
  front/src/utils/firebase/index.ts
  front/src/utils/firebase/onAuthStateChanged.ts
Labels: Logic, Review Required
