Repository uplim/triplate-app, pull requests merged in 2023-03, with the labels that each got.

#7 firebaseのセットアップ
  front/src/lib/firebase.ts
  front/src/pages/_app.tsx
Labels: 🥳LGTM

#5 storybookをデプロイする
  .github/workflows/ci.yml
  .github/workflows/deploy-storybook.yml
  front/package.json
Labels: 🥳LGTM

#8 カラーテーマの設定
  front/src/stories/Colors.stories.mdx
  front/src/styles/global.scss
Labels: 🥳LGTM

#13 フォント設定
  front/src/pages/index.tsx
  front/src/stories/Typography.stories.mdx
  front/src/styles/global.scss
Labels: 🥳LGTM

#14 containerコンポーネント作成
  front/.gitignore
  front/src/components/Containers/Container.tsx
  front/src/components/Containers/index.ts
  front/src/stories/components/Containers/Container.stories.tsx
  front/src/styles/components/Containers/Container.module.scss
  front/src/styles/variables.scss
Labels: Review Required

#18 RTKQueryのセットアップ
  front/package.json
  front/src/pages/_app.tsx
  front/src/redux/api/baseApi.ts
  front/src/redux/store.ts
  front/yarn.lock
Labels: Review Required

#17 PWA化する
  front/next.config.js
  front/package.json
  front/public/favicon-16x16.png
  front/public/favicon-32x32.png
  front/public/icon-192x192.png
  front/public/icon-256x256.png
  front/public/icon-384x384.png
  front/public/icon-512x512.png
  front/public/manifest.json
  front/public/mstile-150x150.png
  front/public/safari-pinned-tab.svg
  front/src/pages/_document.tsx
  front/yarn.lock
Labels: 🥳LGTM

#21 アイコンギャラリー作成
  .github/PULL_REQUEST_TEMPLATE.md
  front/src/stories/cores/Colors.stories.mdx
  front/src/stories/cores/Icons.stories.mdx
  front/src/stories/cores/Typography.stories.mdx
Labels: 🥳LGTM

#23 ２種類ボタンコンポーネント作成
  front/src/components/Buttons/ButtonFill.tsx
  front/src/components/Buttons/ButtonOutline.tsx
  front/src/components/Buttons/index.ts
  front/src/stories/components/Buttons/ButtonFill.stories.tsx
  front/src/stories/components/Buttons/ButtonOutline.stories.tsx
  front/src/styles/components/Buttons/ButtonFill.module.scss
  front/src/styles/components/Buttons/ButtonOutline.module.scss
Labels: 🥳LGTM

#27 セルフレビューとイシューテンプレート
  .github/ISSUE_TEMPLATE/feature.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🥳LGTM

#22 ボトムナビゲーション作成
  front/.storybook/main.js
  front/.storybook/preview.js
  front/package.json
  front/src/components/Layouts/Layout.tsx
  front/src/components/Layouts/index.ts
  front/src/components/Navigations/NavigationBottom.tsx
  front/src/components/Navigations/index.ts
  front/src/pages/_app.tsx
  front/src/pages/home.tsx
  front/src/pages/mypage.tsx
  front/src/pages/search.tsx
  front/src/stories/components/Layouts/Layout.stories.tsx
  front/src/stories/components/Navigations/NavigationBottom.stories.tsx
  front/src/styles/components/Containers/Container.module.scss
  front/src/styles/components/Layouts/Layout.module.scss
  front/src/styles/components/Navigations/NavigationBottom.module.scss
  front/yarn.lock
Labels: Markup, Review Required

#30 issueテンプレート修正
  .github/ISSUE_TEMPLATE/feature.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Review Required

#31 :ribbon: mypageページのマークアップ
  front/public/images/user_sample.jpeg
  front/src/components/Avatars/Avatar.tsx
  front/src/components/Avatars/index.ts
  front/src/components/Buttons/ButtonOutline.tsx
  front/src/components/Containers/Container.tsx
  front/src/components/Grids/GridIconWithText.tsx
  front/src/components/Grids/index.ts
  front/src/components/Icons/IconWithText.tsx
  front/src/components/Icons/index.ts
  front/src/components/Navigations/NavigationBottom.tsx
  front/src/pages/mypage.tsx
  front/src/stories/components/Buttons/ButtonFill.stories.tsx
  front/src/stories/components/Buttons/ButtonOutline.stories.tsx
  front/src/stories/components/Containers/Container.stories.tsx
  front/src/stories/components/Grids/GridIconWithText.stories.tsx
  front/src/stories/components/Icons/IconWithText.stories.tsx
  front/src/stories/components/Layouts/Layout.stories.tsx
  front/src/styles/components/Avatars/Avatar.module.scss
  front/src/styles/components/Containers/Container.module.scss
  front/src/styles/components/Grids/GridIconWithText.module.scss
  front/src/styles/components/Icons/IconWithText.module.scss
  front/src/styles/components/Layouts/Layout.module.scss
  front/src/styles/components/Navigations/NavigationBottom.module.scss
  front/src/styles/components/Pages/Mypage.module.scss
  front/src/styles/global.scss
  front/src/styles/utils.scss
Labels: 🥳LGTM, Markup

#33 🎧 headerコンポーネント作成
  front/src/components/Headers/Header.tsx
  front/src/components/Headers/index.ts
  front/src/pages/index.tsx
  front/src/stories/components/Headers/Header.stories.tsx
  front/src/styles/components/Headers/Header.module.scss
  front/src/styles/components/Icons/IconWithText.module.scss
Labels: Markup, Review Required

#32 :tophat: TabDaysコンポーネント作成
  front/next.config.js
  front/package.json
  front/src/components/Tabs/TabDays.tsx
  front/src/components/Tabs/index.ts
  front/src/stories/components/Tabs/TabDays.stories.tsx
  front/src/styles/components/Buttons/ButtonFill.module.scss
  front/src/styles/components/Buttons/ButtonOutline.module.scss
  front/src/styles/components/Grids/GridIconWithText.module.scss
  front/src/styles/components/Tabs/TabDays.module.scss
  front/src/styles/variables.scss
Labels: 🥳LGTM, Markup

#39 :alien: SEO設定
  front/next.config.js
  front/src/config/next-seo.config.ts
  front/src/pages/_app.tsx
  front/src/pages/index.tsx
  front/src/pages/mypage.tsx
  front/src/styles/components/Containers/Container.module.scss
Labels: 🥳LGTM

#43 メモリ使用量を１GBに制限
  docker-compose.yml
Labels: 🥳LGTM
