Repository uplim/triplate-app, pull requests merged in 2023-06, with the labels that each got.

#116 📵triplinkを/homeに表示させる
  front/firebase/seeds/firestore/triplink.json
  front/firebase/seeds/firestore/users.json
  front/src/components/Auths/CheckAuth.tsx
  front/src/components/Tabs/TabHome.tsx
  front/src/hooks/auths/useCheckAuth.ts
  front/src/pages/home/index.tsx
  front/src/pages/user/new.tsx
  front/src/redux/services/firestore/index.ts
  front/src/redux/services/firestore/triplinks/triplinks.ts
  front/src/redux/stores/auths/authSlice.ts
  front/src/stories/components/Tabs/TabHome.stories.tsx
Labels: 🥳LGTM, Logic

#123 🧥 汎用的なフォームコンポーネントを作成
  front/src/components/Buttons/ButtonFill.tsx
  front/src/components/Buttons/ButtonIconRound.tsx
  front/src/components/Buttons/ButtonIconWithText.tsx
  front/src/components/Buttons/ButtonOutline.tsx
  front/src/components/Buttons/ButtonSmall.tsx
  front/src/components/Buttons/FloatingActionButton.tsx
  front/src/components/Forms/FormCreateUpdateTriplinks.tsx
  front/src/components/Forms/index.ts
  front/src/components/Inputs/InputImage.tsx
  front/src/components/Inputs/InputLabel.tsx
  front/src/components/Inputs/InputText.tsx
  front/src/components/Inputs/InputTextArea.tsx
  front/src/components/Inputs/index.ts
  front/src/pages/triplink/new.tsx
  front/src/stories/components/Forms/FormCreate.stories.tsx
  front/src/stories/components/Forms/FormCreateUpdateTriplinks.stories.tsx
  front/src/stories/components/Inputs/InputLabel.stories.tsx
  front/src/stories/components/Inputs/InputTextArea.stories.tsx
  front/src/styles/components/Forms/FormCreateUpdateTriplinks.styles.ts
  front/src/styles/components/Inputs/InputLabel.styles.ts
  front/src/styles/components/Inputs/InputTextArea.styles.ts
Labels: Markup, Review Required

#125 ⏱️ 画像upload機能，storageの設計
  Makefile
  front/Dockerfile
  front/firebase/scripts/resetAuth.sh
  front/firebase/scripts/resetStorage.ts
  front/firebase/scripts/seeder.ts
  front/firebase/seeds/firestore/triplink.json
  front/firebase/seeds/firestore/users.json
  front/firebase/seeds/storage/images/triplinks/9bcecdd8-fed9-4d72-8a40-b54c7b9ec05b/thumbnail.jpg
  front/firebase/seeds/storage/images/triplinks/a0bf63a0-0367-11ee-be56-0242ac120002/thumbnail.jpg
  front/firebase/seeds/storage/images/triplinks/b21323a4-05f8-42db-9ce7-a2f29946595f/thumbnail.jpg
  front/firebase/seeds/storage/images/triplinks/b533283c-adde-4107-aa0a-943ddccb5278/thumbnail.jpg
  front/firebase/seeds/storage/images/users/C00a2gXGLeIXTjhWZbDiWUWe8Whd/profiles/icon.jpg
  front/firebase/seeds/storage/images/users/C5Ja2gXGLeIXTjhWZbDiWUWe8Whd/profiles/icon.jpg
  front/firebase/seeds/storage/users/thumbnail_sample.jpg
  front/next.config.js
  front/package.json
  front/src/components/Forms/FormCreateUpdateTriplink.tsx
  front/src/components/Forms/index.ts
  front/src/components/Inputs/InputImage.tsx
  front/src/hooks/forms/index.ts
  front/src/hooks/forms/useFormCreateUpdateTriplink.ts
  front/src/hooks/inputs/useInputImage.ts
  front/src/lib/firebase.ts
  front/src/pages/triplink/new.tsx
  front/src/redux/rootStore.ts
  front/src/redux/services/firestore/index.ts
  front/src/redux/services/firestore/triplinks/triplinks.ts
  front/src/redux/services/firestore/users/users.ts
  front/src/redux/services/storage/baseStorageApi.ts
  front/src/redux/services/storage/file/file.ts
  front/src/redux/services/storage/index.ts
  front/src/redux/stores/users/userSlice.ts
  front/src/stories/components/Forms/FormCreateUpdateTriplink.stories.tsx
  front/src/stories/components/Forms/FormCreateUpdateTriplinks.stories.tsx
  front/src/styles/components/Forms/FormCreateUpdateTriplink.styles.ts
  front/src/styles/globalStyle.ts
  front/src/utils/storage/getPath.ts
  front/src/utils/storage/index.ts
  front/yarn.lock
Labels: Logic, Review Required

#126 🔢 triplinkIDにする
  front/firebase/seeds/firestore/users.json
  front/src/components/Tabs/TabHome.tsx
  front/src/redux/services/firestore/index.ts
  front/src/redux/services/firestore/triplinks/triplinks.ts
Labels: Logic

#99 🏆CardLinkEditのマークアップ
  front/src/components/Cards/CardTriplinkEdit.tsx
  front/src/components/Cards/index.ts
  front/src/components/Switches/ToggleSwitch.tsx
  front/src/components/Switches/index.ts
  front/src/stories/components/Cards/CardTriplinkEdit.stories.tsx
  front/src/stories/components/Switches/ToggleSwitch.stories.tsx
  front/src/styles/components/Cards/CardTriplinkEdit.styles.ts
  front/src/styles/components/Inputs/InputText.styles.ts
  front/src/styles/components/Switches/ToggleSwitch.styles.ts
Labels: Markup

#134 🏎 explore カードのget
  front/firebase/seeds/firestore/triplates.json
  front/src/components/Cards/CardExplore.tsx
  front/src/components/Cards/index.ts
  front/src/pages/explore/index.tsx
  front/src/redux/services/firestore/index.ts
  front/src/redux/services/firestore/triplates/triplates.ts
  front/src/stories/components/Cards/CardExplore.stories.tsx
  front/src/styles/components/Cards/CardExplore.styles.ts
  front/src/styles/pages/explore/index.styles.ts
Labels: 🥳LGTM, Logic, Markup

#135 👍 ユーザ作成，更新など
  front/firebase/seeds/firestore/index.json
  front/firebase/seeds/firestore/users.json
  front/firebase/utils/createTestUserIfNotExsists.ts
  front/firebase/utils/type.ts
  front/next.config.js
  front/public/logos/instagram_logo.svg
  front/public/logos/twitter_logo.svg
  front/src/components/Cards/CardTriplinkEdit.tsx
  front/src/components/Forms/FormCreateUpdateTriplink.tsx
  front/src/components/Forms/FormCreateUser.tsx
  front/src/components/Forms/FormUpdateUser.tsx
  front/src/components/Forms/index.ts
  front/src/components/Headers/Header.tsx
  front/src/components/Inputs/InputErrorMessage.tsx
  front/src/components/Inputs/InputImage.tsx
  front/src/components/Inputs/InputText.tsx
  front/src/components/Inputs/InputTextArea.tsx
  front/src/components/Inputs/index.ts
  front/src/config/yup.config.ts
  front/src/hooks/auths/useCheckAuth.ts
  front/src/hooks/forms/index.ts
  front/src/hooks/forms/useFormCreateUpdateUser.ts
  front/src/pages/settings/profile.tsx
  front/src/pages/user/new.tsx
  front/src/redux/services/firestore/index.ts
  front/src/redux/services/firestore/indexes/indexes.ts
  front/src/redux/services/firestore/users/users.ts
  front/src/redux/services/storage/file/file.ts
  front/src/redux/stores/auths/authSlice.ts
  front/src/redux/stores/users/userSlice.ts
  front/src/stories/components/Buttons/ButtonSmall.stories.tsx
  front/src/stories/components/Forms/FormCreateUser.stories.tsx
  front/src/stories/components/Forms/FormUpdateUser.stories.tsx
  front/src/stories/components/Inputs/InputErrorMessage.stories.tsx
  front/src/stories/components/Inputs/InputImage.stories.tsx
  front/src/stories/components/Inputs/InputLabel.stories.tsx
  front/src/stories/components/Inputs/InputText.stories.tsx
  front/src/stories/components/Inputs/InputTextArea.stories.tsx
  front/src/stories/cores/Icons.mdx
  front/src/styles/components/Avatars/Avatar.styles.ts
  front/src/styles/components/Buttons/ButtonFill.styles.ts
  front/src/styles/components/Buttons/ButtonOutline.styles.ts
  front/src/styles/components/Forms/FormCreateUser.styles.ts
  front/src/styles/components/Forms/FormUpdateUser.styles.ts
  front/src/styles/components/Inputs/InputErrorMessage.styles.ts
  front/src/styles/components/Inputs/InputImage.styles.ts
  front/src/styles/components/Inputs/InputLabel.styles.ts
  front/src/styles/components/Inputs/InputText.styles.ts
  front/src/styles/components/Inputs/InputTextArea.styles.ts
  front/src/styles/globalStyle.ts
  front/src/styles/pages/user/new.styles.ts
  front/src/styles/theme.ts
  front/src/styles/utils.ts
Labels: Logic, Review Required

#106 🍟triplateの記録を閲覧するページのマークアップ
  front/src/components/Buttons/ButtonWithIcon.tsx
  front/src/components/Buttons/index.ts
  front/src/components/Cards/CardUserProfile.tsx
  front/src/components/Cards/index.ts
  front/src/components/Headers/Header.tsx
  front/src/components/Tabs/TabContent.tsx
  front/src/components/Tabs/TabDaysWithTriplink.tsx
  front/src/components/Tabs/index.ts
  front/src/pages/index.tsx
  front/src/pages/triplate/[triplateId]/index.tsx
  front/src/pages/triplink/[triplinkId]/index.tsx
  front/src/stories/components/Buttons/ButtonWithIcon.stories.ts
  front/src/stories/components/Tabs/TabDaysWithTriplink.stories.tsx
  front/src/styles/components/Buttons/ButtonWithIcon.styles.ts
  front/src/styles/components/Cards/CardUserProfile.styles.ts
  front/src/styles/components/Headers/Header.styles.ts
  front/src/styles/components/Tabs/TabContent.styles.ts
  front/src/styles/pages/triplate/[triplateId]/index.styles.ts
  front/src/styles/theme.ts
Labels: 🥳LGTM, Markup

#142 マイページのマークアップ
  front/src/components/Avatars/Avatar.tsx
  front/src/components/Buttons/ButtonFill.tsx
  front/src/components/Buttons/ButtonSmall.tsx
  front/src/components/Buttons/ButtonWithIcon.tsx
  front/src/components/Buttons/index.ts
  front/src/components/Cards/CardTriplate.tsx
  front/src/components/Cards/index.ts
  front/src/components/Headers/Header.tsx
  front/src/components/Tabs/TabContent.tsx
  front/src/pages/[userId]/follower.tsx
  front/src/pages/[userId]/following.tsx
  front/src/pages/[userId]/index.tsx
  front/src/pages/dashboard/index.tsx
  front/src/pages/explore/index.tsx
  front/src/pages/triplate/[triplateId]/index.tsx
  front/src/stories/components/Buttons/ButtonSmall.stories.tsx
  front/src/stories/components/Buttons/ButtonWithIcon.stories.ts
  front/src/stories/components/Cards/CardTriplate.stories.tsx
  front/src/styles/components/Buttons/ButtonFill.styles.ts
  front/src/styles/components/Buttons/ButtonSmall.styles.ts
  front/src/styles/components/Buttons/ButtonWithIcon.styles.ts
  front/src/styles/components/Cards/CardTriplate.styles.ts
  front/src/styles/pages/[userId]/index.styles.ts
Labels: 🥳LGTM, Markup
